version: '3.11'
services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile

    restart: always
    env_file:
      - dev.env

    depends_on:
      - postgres

    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:setup_app --host 0.0.0.0 --port 8000"



  postgres:
    image: "postgres:14"
    restart: always
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    healthcheck:
      test: CMD-SHELL pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 10s
      retries: 5